apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "stlgarvchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: container-port
      protocol: TCP
      name: http
  selector:
    {{- include "stlgarvchart.selectorLabels" . | nindent 4 }}
