export class UserDetail {
        user_detail_id?: number;
        user_id?: number;
        reg_number?: string;
        role_id?: number;
        aadhar_card_no?: string;
        first_name?: string;
        middle_name?: string;
        last_name?: string;
        user_image?: string;
        address?: string;
        city?: string;
        panchayat_id?: number;
        pincode?: number;
        whatsapp_no?: string;
        date_of_birth?: string;
        age?: number;
        gender?: string;
        blood_group?: string;
        occupation?: string;
        refer_by?: string;
        user_status?: string;
        doctor_speciality?: string;
        doctor_degree?: string;
        paytm_no?: string;
        hospital_name?: string;
        isGPChanged?: number;
        created_date?: string;
        updated_date?: string
}